apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: http-echo-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: http-echo
  namespaceSelector:
    matchNames:
    - echo-apps
  endpoints:
  - port: http
    interval: 15s
    path: /metrics
    honorLabels: true