apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: echo-apps

resources:
- ../../base

patches:
- target:
    kind: Deployment
    name: http-echo
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "128Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "256Mi"

images:
- name: hashicorp/http-echo
  newTag: latest

configMapGenerator:
- name: app-config
  behavior: merge
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=info