apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: http-echo-hpa
  labels:
    app: http-echo
    environment: test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: http-echo
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30 # Set a low value (30%) to make scaling-up happen more easily during demonstration.
# Memory metric is commented out to avoid dual-condition blocking.
# When both CPU and memory are specified, HPA requires BOTH to exceed their thresholds before scaling. Removing memory ensures scaling is triggered by CPU load alone.
#  - type: Resource
#    resource:
#      name: memory
#      target:
#        type: Utilization
#        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 3
      policies:
      - type: Percent
        value: 100
        periodSeconds: 3
    scaleDown:
      stabilizationWindowSeconds: 3
      policies:
      - type: Percent
        value: 50
        periodSeconds: 3