apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: http-echo-hpa
  labels:
    app: http-echo
    environment: test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: http-echo
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60