apiVersion: v1
kind: Service
metadata:
  name: http-echo-service
  labels:
    app: http-echo
    environment: test
spec:
  selector:
    app: http-echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080