name: CI Pipeline

on:
  workflow_dispatch: 
  push:            
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

env:
  CLUSTER_NAME: ci-cluster
  NAMESPACE: echo-apps
  MONITORING_NS: monitoring

jobs:
  ci-pipeline:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup KinD cluster
      run: bash scripts/setup-kind.sh

    - name: Deploy monitoring stack
      run: bash scripts/deploy-monitoring.sh

    - name: Deploy applications
      run: bash scripts/deploy-apps.sh

    - name: Verify deployments
      run: bash scripts/verify-deployment.sh

    - name: Test echo services
      run: bash scripts/test-echo-services.sh

    - name: Run load test
      run: bash scripts/load-test.sh
      id: loadtest

    - name: Post results to PR
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const body = `### 🚀 Load Test Results\n\n${process.env.LOAD_TEST_RESULTS}`;
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,  // 关键修正
            body
          });
      env:
        LOAD_TEST_RESULTS: ${{ steps.loadtest.outputs.results }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ci-results
        path: |
          load-test-results.md
          deployment-logs.txt

    - name: Cleanup cluster
      if: always()
      run: bash scripts/cleanup.sh
